-- =====================================================================
-- Seed complet: 24 gouvernorats + toutes les délégations de Tunisie
-- Idempotent (ON CONFLICT DO NOTHING) - basé sur la colonne code (unique)
-- =====================================================================

INSERT INTO gouvernorat (nom, code) VALUES
  ('Ariana', 'ARIANA'),
  ('Béja', 'BEJA'),
  ('Ben Arous', 'BENAROUS'),
  ('Bizerte', 'BIZERTE'),
  ('Gabès', 'GABES'),
  ('Gafsa', 'GAFSA'),
  ('Jendouba', 'JENDOUBA'),
  ('Kairouan', 'KAIROUAN'),
  ('Kasserine', 'KASSERINE'),
  ('Kébili', 'KEBILI'),
  ('Le Kef', 'LEKEF'),
  ('Mahdia', 'MAHDIA'),
  ('La Manouba', 'LAMANOUBA'),
  ('Médenine', 'MEDENINE'),
  ('Monastir', 'MONASTIR'),
  ('Nabeul', 'NABEUL'),
  ('Sfax', 'SFAX'),
  ('Sidi Bouzid', 'SIDIBOUZID'),
  ('Siliana', 'SILIANA'),
  ('Sousse', 'SOUSSE'),
  ('Tataouine', 'TATAOUINE'),
  ('Tozeur', 'TOZEUR'),
  ('Tunis', 'TUNIS'),
  ('Zaghouan', 'ZAGHOUAN')
ON CONFLICT (code) DO NOTHING;

-- Délégations (rattachées via id_gouv, résolu par sous-requête sur le nom du gouvernorat)
INSERT INTO delegation (id_gouv, nom, code) VALUES
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ariana'), 'La Soukra', 'ARIANA01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ariana'), 'Raoued', 'ARIANA02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ariana'), 'Mnihla', 'ARIANA03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ariana'), 'Ariana Ville', 'ARIANA04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ariana'), 'Ettadhamen', 'ARIANA05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ariana'), 'Kalâat el-Andalous', 'ARIANA06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ariana'), 'Sidi Thabet', 'ARIANA07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Béja'), 'Béja Nord', 'BEJA01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Béja'), 'Nefza', 'BEJA02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Béja'), 'Medjez el-Bab', 'BEJA03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Béja'), 'Béja Sud', 'BEJA04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Béja'), 'Testour', 'BEJA05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Béja'), 'Téboursouk', 'BEJA06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Béja'), 'Amdoun', 'BEJA07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Béja'), 'Goubellat', 'BEJA08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Béja'), 'Thibar', 'BEJA09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'El Mourouj', 'BENARO01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'Fouchana', 'BENARO02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'Mohamedia', 'BENARO03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'Mornag', 'BENARO04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'Radès', 'BENARO05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'Medina Jedida', 'BENARO06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'Bou Mhel el-Bassatine', 'BENARO07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'Hammam Lif', 'BENARO08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'Ezzahra', 'BENARO09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'Hammam Chott', 'BENARO10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'Ben Arous', 'BENARO11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Ben Arous'), 'Mégrine', 'BENARO12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Bizerte Nord', 'BIZERT01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Bizerte Sud', 'BIZERT02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Ras Jebel', 'BIZERT03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Menzel Bourguiba', 'BIZERT04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Menzel Jemil', 'BIZERT05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Mateur', 'BIZERT06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Sejnane', 'BIZERT07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'El Alia', 'BIZERT08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Joumine', 'BIZERT09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Ghezala', 'BIZERT10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Zarzouna', 'BIZERT11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Utique', 'BIZERT12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Ghar El Melh', 'BIZERT13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Bizerte'), 'Tinja', 'BIZERT14'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'Gabès Sud', 'GABES01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'El Hamma', 'GABES02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'Mareth-Dkhila', 'GABES03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'Gabès Médina', 'GABES04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'Gabès Ouest', 'GABES05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'Ghannouch', 'GABES06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'El Hamma Ouest', 'GABES07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'Oudhref', 'GABES08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'Nouvelle Matmata', 'GABES09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'Métouia', 'GABES10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'Menzel El Habib', 'GABES11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'Toujane', 'GABES12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gabès'), 'Matmata', 'GABES13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'Gafsa Sud', 'GAFSA01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'Métlaoui', 'GAFSA02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'El Ksar', 'GAFSA03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'Moularès', 'GAFSA04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'Redeyef', 'GAFSA05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'Sened', 'GAFSA06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'El Guettar', 'GAFSA07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'Mdhilla', 'GAFSA08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'Zannouch', 'GAFSA09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'Belkhir', 'GAFSA10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'Sidi Aïch', 'GAFSA11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'Gafsa Nord', 'GAFSA12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Gafsa'), 'Sidi Boubaker', 'GAFSA13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Jendouba'), 'Jendouba', 'JENDOU01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Jendouba'), 'Ghardimaou', 'JENDOU02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Jendouba'), 'Tabarka', 'JENDOU03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Jendouba'), 'Fernana', 'JENDOU04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Jendouba'), 'Jendouba Nord', 'JENDOU05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Jendouba'), 'Bou Salem', 'JENDOU06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Jendouba'), 'Balta-Bou Aouane', 'JENDOU07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Jendouba'), 'Aïn Draham', 'JENDOU08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Jendouba'), 'Oued Meliz', 'JENDOU09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Kairouan Nord', 'KAIROU01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Kairouan Sud', 'KAIROU02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Bou Hajla', 'KAIROU03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Sbikha', 'KAIROU04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Haffouz', 'KAIROU05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Hajeb El Ayoun', 'KAIROU06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Chebika', 'KAIROU07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'El Alâa', 'KAIROU08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Echrarda', 'KAIROU09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Oueslatia', 'KAIROU10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Nasrallah', 'KAIROU11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Menzel Mehiri', 'KAIROU12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kairouan'), 'Aïn Djeloula', 'KAIROU13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Sbeïtla', 'KASSER01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Kasserine Nord', 'KASSER02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Fériana', 'KASSER03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Foussana', 'KASSER04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Sbiba', 'KASSER05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Thala', 'KASSER06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Majel Bel Abbès', 'KASSER07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Kasserine Sud', 'KASSER08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Ezzouhour', 'KASSER09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Hassi El Ferid', 'KASSER10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'El Ayoun', 'KASSER11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Jedelienne', 'KASSER12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kasserine'), 'Haïdra', 'KASSER13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kébili'), 'Kébili Nord', 'KEBILI01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kébili'), 'Kébili Sud', 'KEBILI02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kébili'), 'Douz Nord', 'KEBILI03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kébili'), 'Souk Lahad', 'KEBILI04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kébili'), 'Douz Sud', 'KEBILI05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kébili'), 'Faouar', 'KEBILI06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Kébili'), 'Rjim Maatoug', 'KEBILI07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'Kef Est', 'LEKEF01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'Kef Ouest', 'LEKEF02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'Tajerouine', 'LEKEF03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'Dahmani', 'LEKEF04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'Sers', 'LEKEF05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'Nebeur', 'LEKEF06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'Sakiet Sidi Youssef', 'LEKEF07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'El Ksour', 'LEKEF08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'Kalaat Senan', 'LEKEF09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'Jérissa', 'LEKEF10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'Touiref', 'LEKEF11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Le Kef'), 'Kalâat Khasba', 'LEKEF12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'Mahdia', 'MAHDIA01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'Essouassi', 'MAHDIA02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'El Jem', 'MAHDIA03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'Sidi Alouane', 'MAHDIA04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'Ksour Essef', 'MAHDIA05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'Bou Merdes', 'MAHDIA06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'Chebba', 'MAHDIA07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'Chorbane', 'MAHDIA08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'Ouled Chamekh', 'MAHDIA09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'Melloulèche', 'MAHDIA10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'El Bradâa', 'MAHDIA11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'Hebira', 'MAHDIA12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Mahdia'), 'Rejiche', 'MAHDIA13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'La Manouba'), 'Douar Hicher', 'LAMANO01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'La Manouba'), 'Oued Ellil', 'LAMANO02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'La Manouba'), 'La Manouba', 'LAMANO03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'La Manouba'), 'Djedeida', 'LAMANO04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'La Manouba'), 'Tebourba', 'LAMANO05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'La Manouba'), 'Mornaguia', 'LAMANO06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'La Manouba'), 'Borj El Amri', 'LAMANO07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'La Manouba'), 'El Batan', 'LAMANO08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Médenine'), 'Ben Gardane', 'MEDENI01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Médenine'), 'Zarzis', 'MEDENI02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Médenine'), 'Medenine Nord', 'MEDENI03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Médenine'), 'Médenine Sud', 'MEDENI04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Médenine'), 'Sidi Makhlouf', 'MEDENI05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Médenine'), 'Beni Khedache', 'MEDENI06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Médenine'), 'Djerba', 'MEDENI07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Monastir', 'MONAST01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Moknine', 'MONAST02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Jemmal', 'MONAST03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Ksar Hellal', 'MONAST04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Ksibet el-Médiouni', 'MONAST05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Téboulba', 'MONAST06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Bembla', 'MONAST07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Sahline', 'MONAST08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Zéramdine', 'MONAST09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Bou Hajar', 'MONAST10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Ouerdanine', 'MONAST11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Bekalta', 'MONAST12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Monastir'), 'Beni Hassen', 'MONAST13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Grombalia', 'NABEUL01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Korba', 'NABEUL02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Nabeul', 'NABEUL03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Soliman', 'NABEUL04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Menzel Temime', 'NABEUL05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Kélibia', 'NABEUL06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Dar Chaâbane El Fehri', 'NABEUL07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Béni Khiar', 'NABEUL08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'El Haouaria', 'NABEUL09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Béni Khalled', 'NABEUL10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Menzel Bouzelfa', 'NABEUL11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Bou Argoub', 'NABEUL12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'El Mida', 'NABEUL13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Takelsa', 'NABEUL14'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Nabeul'), 'Hammam Ghezèze', 'NABEUL15'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Sfax Sud', 'SFAX01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Sakiet Eddaïer', 'SFAX02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Sfax Ouest', 'SFAX03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Sfax Ville', 'SFAX04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Sakiet Ezzit', 'SFAX05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Thyna', 'SFAX06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Jebiniana', 'SFAX07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'El Hencha', 'SFAX08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Bir Ali Ben Khalifa', 'SFAX09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Agareb', 'SFAX10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Menzel Chaker', 'SFAX11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Skhira', 'SFAX12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'El Amra', 'SFAX13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Mahrès', 'SFAX14'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Graïba', 'SFAX15'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sfax'), 'Kerkennah', 'SFAX16'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Sidi Bouzid Ouest', 'SIDIBO01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Sidi Bouzid Est', 'SIDIBO02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Regueb', 'SIDIBO03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Jilma', 'SIDIBO04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Bir El Hafey', 'SIDIBO05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Sidi Ali Ben Aoun', 'SIDIBO06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Menzel Bouzaiane', 'SIDIBO07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Essaïda', 'SIDIBO08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Mezzouna', 'SIDIBO09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Souk Jedid', 'SIDIBO10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Cebbala Ouled Asker', 'SIDIBO11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Meknassy', 'SIDIBO12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Ouled Haffouz', 'SIDIBO13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sidi Bouzid'), 'Hichria', 'SIDIBO14'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Siliana'), 'Siliana Sud', 'SILIAN01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Siliana'), 'Siliana Nord', 'SILIAN02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Siliana'), 'Makthar', 'SILIAN03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Siliana'), 'Rouhia', 'SILIAN04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Siliana'), 'El Krib', 'SILIAN05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Siliana'), 'Bou Arada', 'SILIAN06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Siliana'), 'Gaâfour', 'SILIAN07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Siliana'), 'Kesra', 'SILIAN08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Siliana'), 'Sidi Bou Rouis', 'SILIAN09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Siliana'), 'Bargou', 'SILIAN10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Siliana'), 'El Aroussa', 'SILIAN11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Jawhara', 'SOUSSE01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'M''saken', 'SOUSSE02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Riadh', 'SOUSSE03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Kalâa Kebira', 'SOUSSE04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Enfida', 'SOUSSE05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Sidi Abdelhamid', 'SOUSSE06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Zaouiet Ksibet Thrayet', 'SOUSSE07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Hammam Sousse', 'SOUSSE08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Kalâa Seghira', 'SOUSSE09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Akouda', 'SOUSSE10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Bouficha', 'SOUSSE11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Sousse Médina', 'SOUSSE12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Sidi Bou Ali', 'SOUSSE13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Kondar', 'SOUSSE14'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Sidi El Hani', 'SOUSSE15'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Sousse'), 'Hergla', 'SOUSSE16'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tataouine'), 'Tataouine Nord', 'TATAOU01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tataouine'), 'Tataouine Sud', 'TATAOU02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tataouine'), 'Ghomrassen', 'TATAOU03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tataouine'), 'Bir Lahmar', 'TATAOU04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tataouine'), 'Remada', 'TATAOU05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tataouine'), 'Beni Mhira', 'TATAOU06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tataouine'), 'Smâr', 'TATAOU07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tataouine'), 'Dehiba', 'TATAOU08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tozeur'), 'Tozeur', 'TOZEUR01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tozeur'), 'Degache', 'TOZEUR02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tozeur'), 'Nefta', 'TOZEUR03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tozeur'), 'El Hamma du Jerid', 'TOZEUR04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tozeur'), 'Tameghza', 'TOZEUR05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tozeur'), 'Hazoua', 'TOZEUR06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Sidi Hassine', 'TUNIS01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Hraïria', 'TUNIS02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'La Marsa', 'TUNIS03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Le Kram', 'TUNIS04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'El Kabaria', 'TUNIS05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Le Bardo', 'TUNIS06'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'El Omrane supérieur', 'TUNIS07'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'La Goulette', 'TUNIS08'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'El Menzah', 'TUNIS09'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'El Omrane', 'TUNIS10'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Ezzouhour', 'TUNIS11'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Cité El Khadra', 'TUNIS12'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Bab El Bhar', 'TUNIS13'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'El Ouardia', 'TUNIS14'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Séjoumi', 'TUNIS15'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Bab Souika', 'TUNIS16'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Sidi El Béchir', 'TUNIS17'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Djebel Jelloud', 'TUNIS18'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Carthage', 'TUNIS19'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Ettahrir', 'TUNIS20'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Tunis'), 'Médina', 'TUNIS21'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Zaghouan'), 'El Fahs', 'ZAGHOU01'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Zaghouan'), 'Zaghouan', 'ZAGHOU02'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Zaghouan'), 'Nadhour', 'ZAGHOU03'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Zaghouan'), 'Zriba', 'ZAGHOU04'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Zaghouan'), 'Bir Mcherga', 'ZAGHOU05'),
  ((SELECT id_gouv FROM gouvernorat WHERE nom = 'Zaghouan'), 'Saouaf', 'ZAGHOU06')
ON CONFLICT (code) DO NOTHING;
